# Generated by Django 4.2.7 on 2024-02-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_collected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('id_number', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('model_description', models.CharField(max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_shipping_cost_paid', models.BooleanField(default=False)),
                ('expected_delivery_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='payment',
            name='shipping_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PracApp.shippinginfo'),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PracApp.shippinginfo'),
        ),
    ]
