# Generated by Django 4.2.7 on 2024-02-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0002_item_payment_shippinginfo_delete_feature_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingInfo',
            new_name='Shipment',
        ),
    ]
