# Generated by Django 4.2.7 on 2024-02-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0003_rename_shippinginfo_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shipping_info',
            new_name='shipment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='shipping_info',
            new_name='shipment',
        ),
    ]
