# Generated by Django 4.2.7 on 2024-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0005_remove_item_quantity_shipment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
