# Generated by Django 4.2.7 on 2024-03-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0006_shipment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='model_description',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.AddField(
            model_name='shipment',
            name='Sender_id',
            field=models.CharField(default='OLD ROWS', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_description',
            field=models.CharField(default='OLD ROWS', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_name',
            field=models.CharField(default='OLD ROWS', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reciever_address',
            field=models.TextField(default='OLD ROWS'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reciever_id',
            field=models.CharField(default='OLD ROWS', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reciever_name',
            field=models.CharField(default='OLD ROWS', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_address',
            field=models.TextField(default='OLD ROWS'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(default='OLD ROWS', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default='OLD ROWS', max_digits=10),
        ),
    ]
