# Generated by Django 4.2.7 on 2024-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0008_remove_payment_shipment_remove_shipment_sender_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='package_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='package_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_id',
            field=models.CharField(max_length=50),
        ),
    ]
