# Generated by Django 4.2.7 on 2024-03-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracApp', '0009_alter_shipment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(default='Me', max_length=200),
        ),
    ]
